# Generated by Django 4.2.30 on 2026-04-17 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отдела')),
                ('manager', models.CharField(max_length=100, verbose_name='Руководитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='HRMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('turnover', 'Текучесть кадров'), ('engagement', 'Вовлечённость'), ('performance', 'Производительность'), ('satisfaction', 'Удовлетворённость'), ('absence', 'Пропуски')], max_length=20, verbose_name='Тип метрики')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('date_recorded', models.DateField(verbose_name='Дата записи')),
                ('target_value', models.FloatField(default=0, verbose_name='Целевое значение')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department', verbose_name='Отдел')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Записал')),
            ],
            options={
                'verbose_name': 'HR-метрика',
                'verbose_name_plural': 'HR-метрики',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Дата приёма')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарплата')),
                ('performance_score', models.FloatField(default=0, verbose_name='Оценка производительности')),
                ('engagement_score', models.FloatField(default=0, verbose_name='Вовлечённость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
